full_name = input("Enter your full name")
id = input("Entetr your id")
departmert = input("Enter your department")
year = input("Enter your academic year")
University = input("Enter your university")
phone = input("Enter your phone number")

print("+--------------------------------+")
print("|       AKIBA STUDENT CARD       |")
print("+--------------------------------+")
print(f"| Name : {full_name}            |")
print(f"| ID : {id}                     |")
print(f"| Department : {departmert}     |")
print(f"| Year : {year}                 |")
print(f"| University : {University}     |")
print(f"| Phone : {phone}               |")
print("+--------------------------------+")