full_name = input("Enter your full name: ")
age = int(input("Enter your age: "))
student_id = input("Enter your student id: ")
city = input("Enter your city: ")
university = input("Enter your university: ")
department = input("Enter your department: ")
email = input("Enter your email: ")
phone = input("Enter your phone number: ")
favorite_language = input("Enter your favorite programming language: ")
programming_goal = input("Enter your programming goal: ")

print("================================================")
print("              AKIBA STUDENT PROFILE")
print("================================================")

print(f"Name:                 {full_name}")
print(f"Student ID:           {student_id}")
print(f"Age:                  {age}")
print(f"City:                 {city}")
print(f"University:           {university}")
print(f"Department:           {department}")
print(f"Email:                {email}")
print(f"Phone:                {phone}")
print(f"Favorite Language:    {favorite_language}")

print()
print("Programming Goal:")
print(programming_goal)

print()
print("================================================")
